name: notes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  # koneksi api
  dio: ^4.0.6 
  
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  # state management 
  flutter_riverpod: ^2.0.0 
  flutter_screenutil: ^5.7.0
  flutter_svg: 2.0.2
  freezed: ^2.1.1
  # router
  go_router: ^4.5.1
  google_fonts: ^3.0.1
  # local
  hive_flutter: ^1.1.0
  # modal / dialog  box
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
